name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^9.1.1

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^8.2.0
  
  #dateFormat
  intl: ^0.20.2

  #Database
  floor: any

  #make request to api
  retrofit: ^4.7.1

  # Firebase
  firebase_core: ^2.24.0
  cloud_firestore: ^4.13.3
  firebase_storage: ^11.5.5

  # Para seleccionar imÃ¡genes desde el dispositivo
  image_picker: ^1.0.7


  #Hooks
  flutter_hooks: ^0.21.2

  #chached image 
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^9.2.0
  floor_generator: ^1.5.0
  build_runner: ^2.5.4
  

flutter:

  uses-material-design: true

 
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
